# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'breweries-list' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for breweries-list
  pod 'R.swift'
  pod 'SQLite.swift', '~> 0.12.0'
  pod 'AppusViper', :git => 'https://gitlab.appus.software/ios/VIPER-template.git', :branch => 'viper-2'
end
